mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include("polls.urls")),
    # Khai báo toàn bộ file urls.py trong polls
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path
from . import views 

app_name = 'polls'
urlpatterns = [
    path('detail/<int:question_id>', views.detailView, name = 'detail'),
    path('list/', views.viewlist, name = 'view_list'),
    path('', views.index, name="index"),
    path('<int:question_id>', views.vote, name="vote"),
    path('abc/', views.ham1, name="ham1"),
]

mysite/polls/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    # Độ dài câu hỏi
    question_test = models.CharField(max_length=200)
    #Thời gian đưa ra
    time_pub = models.DateTimeField()

class Choice(models.Model):
    # Xóa câu trả lời
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    #Nội dung câu trả lời
    choice_text = models.CharField(max_length=100)
    # Điểm số của các câu trả lời
    vote = models.IntegerField(default=0)

mysite/polls/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Question

# Create your views here.

def index(request):
    myname = "Nguyễn Sơn"
    taisan = {"Điện thoại", "Máy tính", "Máy bay", "Nhiều tiền"}
    context = {"name": myname, "taisan": taisan}
    return render(request, "polls/index.html", context)

def viewlist(request):
    list_question = Question.objects.all()
    context = {"dsquest":list_question}
    return render(request, "polls/question_list.html", context)

def detailView(request, question_id):
    q = Question.objects.get(pk = question_id)
    return render(request, "polls/detail_Question.html", {"qs": q})

def vote(request, question_id):
    q = Question.objects.get(pk = question_id)
    try:
        dulieu = request.POST["choice"]
        c = q.choice_set.get(pk = dulieu)
    except:
        HttpResponse("lỗi không có choice")
    c.vote += 1
    c.save()
    return render(request, 'polls/result.html', {'q':q})

def ham1(request):
    return HttpResponse("<h1>Hàm linh tinh</h1><p>Xin chào</p>")

mysite/polls/templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base</title>
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
</head>
<body>
    <div class="header">
        <h1>My website</h1>
    </div>
    <div class="menu">
        <ul>
            <li><a href="#">Link1</a></li>
            <li><a href="#">Link2</a></li>
            <li><a href="#">Link3</a></li>
            <li><a href="#">Link4</a></li>
        </ul>
    </div>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
    <div class="noidung">
        {% block content123 %}
        {% endblock %}
    </div>
    <div class="content1">
        {% block content321 %}
        {% endblock %}
    </div>
    <div class="content1">
        {% block content234 %}
        {% endblock %}
    </div>
</body>
</html>

mysite/polls/templates/polls/detail_Question.html
{% extends 'polls/base.html' %}

{% block content321 %}
    {% if qs %}
        <h1>{{ qs.question_test }}</h1>
        <form action="{% url 'polls:vote' qs.id %}" method="post">
            <!-- Lỗi bảo mật -->
            {% csrf_token %}
            <ul>
            {% for item in qs.choice_set.all %}
                <li><input type="radio" value="{{ item.id }}" name="choice">{{ item.choice_text }}</li>
            {% endfor %}
            <p><input type="submit" value="gửi"></p>
        </ul>
        </form>
    {% endif %}

{% endblock %}

mysite/polls/templates/polls/index.html
{% extends 'polls/base.html' %}
    {% block content %}
    <h1>Đây là template</h1>
    <p>Chào các bạn, mình là <b>{{ name }}</b></p>
    <h2>Tài sản của tôi gồm: </h2>
    <ul>
        {%  for item in taisan %}
            {% if item != "Máy tính" %}
                <li>{{ item }}</li>
            {% endif %}
        {% endfor %}
    </ul>
{% endblock %}

mysite/polls/templates/polls/question_list.html
{% extends 'polls/base.html' %}
    {% block content123 %}
        {% if dsquest %}
            {% for item in dsquest %}
                <a href="{% url 'polls:detail' item.id %}"><p>{{ item.question_test }}</p></a>
            {% endfor %}
        {% else %}
            <h3 style="color:red">Không có dữ liệu câu hỏi nào!!</h3>
        {% endif %}
    {% endblock %}

mysite/polls/templates/polls/result.html
{% extends 'polls/base.html' %}
{% block content234 %}
    {% if q %}
        <h1>{{ q.question_test }}</h1>
        <p>Kết quả của cuộc bình chọn là: </p>
        {% for item in q.choice_set.all %}
            <p>{{ item.choice_text}}:<span style="color:red">{{ item.vote }}</span></p>
        {% endfor %}
        <a href="{% url 'polls:view_list' %}">Vote tiếp</a>
    {% endif %}
{% endblock %}