DjangoForm/demoform/demoform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
]

DjangoForm/demoform/news/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('email/', views.email_view, name = 'email'),
    path('add_save/', views.Save.as_view(), name='save'),
    path('', views.index, name = "index"),
    # path('add/', views.add_post, name = 'add'),
    path('process/', views.process, name = 'process'),
]

DjangoForm/demoform/news/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=255, blank=False, null = False)
    content = models.TextField(max_length = 1000, blank = False, null  = False)
    time_create = models.DateField(default = timezone.now())

    def __str__(self):
        return self.title

DjangoForm/demoform/news/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'time_create', )
        widget = {
            'title':forms.TextInput(attrs={'class':'sonnguyen'})
        }

class SendEmail(forms.Form):
    title = forms.CharField(max_length=100, widget = forms.TextInput(attrs = {'class':'tieude'}))
    email = forms.EmailField()
    content = forms.CharField(widget=forms.Textarea(attrs = {'class':'nguyenson'}))
    cc = forms.BooleanField(required=False)

DjangoForm/demoform/news/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import PostForm, SendEmail
from django.views import View
# Create your views here.
def index(request):
    return HttpResponse("Hello")

# def add_post(request):
#     a = PostForm()
#     return render(request, 'news/add_news.html', {'f':a})


# class Post(View):
#     def get(self, request):
#         a = PostForm()
#         return render(request, 'news/add_new.html')


class Save(View):
    
    def get(self, request):
        a = PostForm()
        return render(request, 'news/add_news.html', {'f':a})

    def post(self, request):
        q = PostForm(request.POST)
        if q.is_valid():
            q.save()
            return HttpResponse('Success!!')
        else:
            return HttpResponse('not validate!!')

# def save_news(request):
#     if request.method == 'POST':
#         q = PostForm(request.POST)
#         if q.is_valid():
#             q.save()
#             return HttpResponse('Luu thanh cong!')
#         else:
#             return HttpResponse('Khong duoc validate')
#     else:
#         return HttpResponse("Khong phai post request")
    
def email_view(request):
    b = SendEmail()
    return render(request, 'news/email.html', {'f':b})

def process(request):
    if request.method == 'POST':
        q = SendEmail(request.POST)
        if q.is_valid():
            title = q.cleaned_data['title']
            email = q.cleaned_data['email']
            content = q.cleaned_data['content']
            cc = q.cleaned_data['cc']
            context = {'td':title, 'c':cc, 'ct':content, 'e':email}
            context2 = {'email_data':q}
            return render(request, 'news/print_email.html', context)
        else:
            return HttpResponse("form not validate")
    else:
        return HttpResponse('Khong phai POST method')

DjangoForm/demoform/news/templates/news/add_news.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action=" {% url 'news:save' %}" method="post">
        {% csrf_token %}
        <p>{{ f.title }}</p>
        <p>{{ f.content }}</p>
        <p>{{ f.time_create }}</p>
        <input type="submit" value="submit">
    </form>
</body>
</html>

DjangoForm/demoform/news/templates/news/email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .nguyenson{
            background-color: aliceblue;
        }
    </style>
</head>
<body>
    <form action="{% url 'news:process' %}" method="post">
        {% csrf_token %}
        {{ f }}
        <input type="submit" value="send">
    </form>
</body>
</html>

DjangoForm/demoform/news/templates/news/print_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        td{
            border:1px solid #000;
        }
    </style>
</head>
<body>
    <table>
        <tr>
            <td>Title</td>
            <td>Content</td>
            <td>Email</td>
            <td>CC</td>
        </tr>
        <tr>
            <td>{{ td }}</td>
            <td>{{ ct }}</td>
            <td>{{ e }}</td>
            <td>{{ c }}</td>
        </tr>
    </table>
</body>
</html>